# Generated by Django 5.2.6 on 2025-09-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos_novos',
            name='dono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
