# Generated by Django 5.2.6 on 2025-09-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_projetos_novos_dono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habili_contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.CharField(max_length=50)),
                ('habilidades', models.TextField()),
                ('contato', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
