# Generated by Django 5.2.6 on 2025-09-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_habili_contatos'),
    ]

    operations = [
        migrations.AddField(
            model_name='habili_contatos',
            name='image',
            field=models.ImageField(null=True, upload_to='projects/'),
        ),
    ]
